# Generated by Django 4.0.6 on 2022-07-23 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0002_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
