# Generated by Django 4.0.6 on 2022-08-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0003_remove_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='gig_or_rehearsal',
            field=models.CharField(choices=[('gig', 'Gig'), ('rehearsal', 'Rehearsal')], default='Gig', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='length_of_set',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lodging',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rate_of_pay',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_contact',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
